### PR TITLE
Fix Bank Menu

### LINKED ISSUE #12: Add error message to `BankMenu`
Currently when a player attempts to deposit/withdraw crystals but doesn't have enough, there is no visual feedback. We should display a clear error message in the `BankMenu` UI.
- Add error message display logic to `BankMenu`
- Ensure message disappears after 3-5 seconds

Notes:
- This error message functionality is already implemented in other menues such as `AnalyzeMenu` or `ShopMenu`

Priority: `Low`

### PR DESCRIPTION
**Pull request by chocolatemilq**
Reformat code to reduce repeated parts. Add messages to inform user that withdrawing or deposit is invalid.

### CODE REVIEW

File: src/Rpg/menues/DepositMenu.cpp [hunk 1]
```diff
@@ -58,66 +34,19 @@ DepositMenu::DepositMenu(sf::RenderWindow& window, const sf::Vector2f position,
 	m500Button.setPosition(sf::Vector2f(mMenuShape.getPosition().x + 300.f + 220.f,
 		mMenuShape.getPosition().y + 25.f - 8.75f));
 	mConfirmButton.setPosition(sf::Vector2f(mMenuShape.getPosition().x + 100.f, mMenuShape.getPosition().y + 310.f));
```
Comment (mihaid11) [inline src/Rpg/menues/DepositMenu.cpp:35]: Remove this line (36)

File: src/Rpg/menues/DepositMenu.h [hunk 2]
```diff
@@ -14,6 +14,8 @@ class DepositMenu
 	void restart();
 
 private:
+	void depositAmount(int amount, int& bankBalance, int& crystals, int& storageCapacity); // called when click desposit buttons
```
Comment (mihaid11) [inline src/Rpg/menues/DepositMenu.h]:
```suggestion
	void depositAmount(int amount, int& bankBalance, int& crystals, int& storageCapacity); // called when deposit buttons are clicked
```

File: src/Rpg/menues/WithdrawMenu.h [hunk 3]
```diff
@@ -14,6 +14,8 @@ class WithdrawMenu
 	void restart();
 
 private:
+	void withdrawAmount(int amount, int& bankBalance); // called when click withdraw buttons
```
Comment (mihaid11) [inline src/Rpg/menues/WithdrawMenu.h]:
```suggestion
	void withdrawAmount(int amount, int& bankBalance); // called when withdraw buttons are clicked
```

**Review by mihaid11 — CHANGES_REQUESTED** [review]
Use present tense for the commit message/PR title. Also, see my inline comments for minor improvements. Thanks!

**Comment by mihaid11** [comment]
Merged! Thanks for your contribution!
